[project]
name = "flight-sim"
version = "0.1.0"
description = "A flight simulation framework"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pymap3d>=3.2.0",
    "scipy>=1.16.3",
]
